lib/blog_web/router.ex
defmodule BlogWeb.Router do
  use BlogWeb, :router

  import BlogWeb.AuthorAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_author
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BlogWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", BlogWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: BlogWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", BlogWeb do
    pipe_through [:browser, :redirect_if_author_is_authenticated]

    get "/authors/register", AuthorRegistrationController, :new
    post "/authors/register", AuthorRegistrationController, :create
    get "/authors/log_in", AuthorSessionController, :new
    post "/authors/log_in", AuthorSessionController, :create
    get "/authors/reset_password", AuthorResetPasswordController, :new
    post "/authors/reset_password", AuthorResetPasswordController, :create
    get "/authors/reset_password/:token", AuthorResetPasswordController, :edit
    put "/authors/reset_password/:token", AuthorResetPasswordController, :update
  end

  scope "/", BlogWeb do
    pipe_through [:browser, :require_authenticated_author]

    get "/authors/settings", AuthorSettingsController, :edit
    put "/authors/settings", AuthorSettingsController, :update
    get "/authors/settings/confirm_email/:token", AuthorSettingsController, :confirm_email
  end

  scope "/posts", BlogWeb do
    pipe_through [:browser]

    resources "/", PostController
  end

  scope "/", BlogWeb do
    pipe_through [:browser]

    delete "/authors/log_out", AuthorSessionController, :delete
    get "/authors/confirm", AuthorConfirmationController, :new
    post "/authors/confirm", AuthorConfirmationController, :create
    get "/authors/confirm/:token", AuthorConfirmationController, :confirm
  end
end

lib/blog_web/views/layout_view.ex
defmodule BlogWeb.LayoutView do
  use BlogWeb, :view
end

lib/blog_web/templates/layout/_author_menu.html.eex
<ul>
<%= if @current_author do %>
  <li><%= @current_author.email %></li>
  <li><%= link "Settings", to: Routes.author_settings_path(@conn, :edit) %></li>
  <li><%= link "Log out", to: Routes.author_session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <li><%= link "Register", to: Routes.author_registration_path(@conn, :new) %></li>
  <li><%= link "Log in", to: Routes.author_session_path(@conn, :new) %></li>
<% end %>
</ul>

lib/blog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Blog · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
          <%= render "_author_menu.html", assigns %>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>